name: apktool_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  archive: ^4.0.7
  xml: ^6.5.0
  path: ^1.9.1
  image: ^4.1.7
  collection: ^1.19.1
  convert: ^3.1.2
  crypto: ^3.0.6
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
