name: apktool_dart
description: A Dart port of apktool
version: 0.1.0
repository: https://github.com/zapstore/apktool_dart

environment:
  sdk: ^3.8.1

dependencies:
  xml: ^6.5.0
  path: ^1.9.1
  image: ^4.1.7
  collection: ^1.19.1
  convert: ^3.1.2
  crypto: ^3.0.6
  args: ^2.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
